### ISSUE TITLE
It does not have image normalization

### ISSUE THREAD

**Issue by mohayl** [IBM/tensorflow-hangul-recognition#33]
if you write small or large character, it will not recognize that character.

**Comment by pvaneck** [comment]
Yea, this is one issue with the trained model as CNNs don't explicitly handle scale variations too well. Since the model is being trained on characters that are pretty much the same scale, there would likely be issues with input images that deviate too much in scale. One way to have the model better handle this is to train the model with images of each character at differing scales using libraries like https://github.com/aleju/imgaug. Though this would greatly increase the amount of data and training time, but would allow the network to be more robust to scale variation. There are a number of research papers describing scale-invariant CNNs, so changing the model architecture is also a possibility, though this would probably be better left as an exercise for developers.

I guess one way to handle this at the application level is to somehow detect large or small hand-drawn characters, and try to scale down/up accordingly to better match the training image size. However, this seems non-trivial, and am inclined to leave it as a limitation for now unless I have more time in the future. Open to contributions though. :)

**Comment by mohayl** [comment]
This problem can be solved by image augmentation. In tensorFlow there are different image augmentation techniques which can also increase the dataset.

**Comment by markstur** [comment]
Closing because I don't think anyone is taking any action on this.
